version: '3.8'

services:
  db:
    image: postgres:15
    container_name: songLib_db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5436:5432"
    volumes:
      - songLib_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/migrations.sql

  app:
    build: ./app
    container_name: songLib_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  songLib_data:
