version: '3.8'

services:
  db:
    image: postgres:15
    container_name: songLib_db
    restart: always
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - songLib_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/migrations.sql

  app:
    build: ./app
    container_name: songLib_app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      APP_PORT: 8080
      EXTERNAL_API_URL: "http://host.docker.internal:8090"
    ports:
      - "8080:8080"

volumes:
  songLib_data:
